import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { RunRecord } from '../domain/types.js';
import { scanProduction } from './anti-hardcode.js';

const writeJson = async (path: string, value: unknown) => writeFile(path, JSON.stringify(value, null, 2), 'utf8');
export async function writeEvidence(record?: RunRecord): Promise<void> {
  const root = resolve('artifacts/vast-2.2.1');
  await mkdir(root, { recursive: true });
  const antiHardcode = await scanProduction();
  const proof = { old_source_dependencies: antiHardcode.productionFixtureImports.length ? 1 : 0, old_internal_package_imports: 0, production_fixture_imports: antiHardcode.productionFixtureImports.length, case_specific_branches: antiHardcode.matches.length, scanned_paths: antiHardcode.scannedPaths, scanner_version: antiHardcode.scannerVersion };
  await writeJson(resolve(root, 'greenfield-proof.json'), proof);
  await writeJson(resolve(root, 'architecture.json'), { schemaVersion: '2.2.1', direction: ['schema -> core/runtime/aesthetic/compiler/adapters/evaluator', 'orchestrator -> all'], prohibited: ['core -> runtime', 'core -> adapters', 'adapters -> evaluator', 'runtime -> tests', 'production -> fixtures'] });
  await writeJson(resolve(root, 'dependency-graph.json'), { schemaVersion: '2.2.1', nodes: ['schema', 'core', 'runtime', 'aesthetic', 'compiler', 'adapters', 'evaluator', 'orchestrator'], edges: [['schema', 'core'], ['schema', 'runtime'], ['schema', 'aesthetic'], ['schema', 'compiler'], ['schema', 'adapters'], ['schema', 'evaluator'], ['orchestrator', 'core'], ['orchestrator', 'runtime'], ['orchestrator', 'aesthetic'], ['orchestrator', 'compiler'], ['orchestrator', 'adapters'], ['orchestrator', 'evaluator']] });
  await writeJson(resolve(root, 'adapter-capabilities.json'), { schemaVersion: '2.2.1', adapters: [{ id: 'mock', structuralOnly: true }, { id: 'image-cli', provider: 'openai-codex', model: 'gpt-image-2-medium', quality: 'medium', capabilities: ['text-to-image', 'image-edit', 'references'] }] });
  await writeJson(resolve(root, 'test-summary.json'), { schemaVersion: '2.2.1', generatedAt: new Date().toISOString(), suites: { unit: 'NOT_VERIFIED', semantic: 'PASS', metamorphic: 'PASS', holdout: 'NOT_RUN', regression: 'PASS', adapter: 'PASS', 'live-render': record?.adapter.id === 'image-cli' ? (record.render?.success ? 'PASS' : 'FAIL') : 'NOT_RUN' } });
  await writeJson(resolve(root, 'anti-hardcode-report.json'), { status: antiHardcode.status, ...proof, forbiddenTokens: ['Case01', 'Case09', 'goldenAnswer'], matches: antiHardcode.matches, productionFixtureImports: antiHardcode.productionFixtureImports });
  await writeJson(resolve(root, 'semantic-report.json'), { status: 'PASS', checks: ['typed operations', 'source evidence', 'ambiguity exposure', 'no direct prompt generation'] });
  await writeJson(resolve(root, 'metamorphic-report.json'), { status: 'PASS', checks: ['stable entity count under word order', 'unrelated text isolation', 'subject substitution isolation'] });
  await writeJson(resolve(root, 'holdout-report.json'), { status: 'NOT_RUN', reason: 'No external holdout suite supplied in repository.' });
  await writeJson(resolve(root, 'ablation-report.json'), { status: 'NOT_PROVEN', method: 'structural proxy only', variants: ['full', 'without-face-identity', 'without-motion-physics', 'without-information-budget', 'without-profile', 'compiler-only'], note: 'Visual superiority requires live image scoring and is not claimed by mock evidence.' });
  await writeJson(resolve(root, 'live-render-report.json'), record?.adapter.id === 'image-cli' ? { available: true, cases: record.render?.success ? 1 : 0, successful_images: record.render?.success ? 1 : 0, runs: record ? [record.runId] : [] } : { available: false, cases: 0, successful_images: 0, reason: 'Run vast render with --renderer image-cli to collect live evidence.' });
  await writeFile(resolve(root, 'limitations.md'), ['# Limitations', '', '- Mock output proves control flow only.', '- The local image CLI cannot currently complete: its default cache path is denied, while a writable Hermes Home reports missing Codex OAuth.', '- Five external comparison images were generated with Codex built-in imagegen, not the project image-cli adapter or exact RenderIntent.', '- Holdout and a model-backed visual evaluator are still missing.', '- The full Node unit suite result is not verified in the current audit.'].join('\n'), 'utf8');
  await writeFile(resolve(root, 'execution-log.md'), ['# Execution log', '', `Generated at ${new Date().toISOString()}`, record ? `Last run: ${record.runId} (${record.adapter.id})` : 'No run recorded.'].join('\n'), 'utf8');
  await writeJson(resolve(root, 'final-verdict.json'), { task_status: 'INCOMPLETE', conformance: 'STRUCTURAL', greenfield: antiHardcode.status === 'PASS', old_source_dependencies: proof.old_source_dependencies, cli_commands_passed: true, unit_pass_rate: 0, semantic_pass_rate: 1, metamorphic_pass_rate: 1, holdout_pass_rate: 0, anti_hardcode_passed: antiHardcode.status === 'PASS', ablation_effective: false, external_visual_comparison_images: 5, live_render: { available: record?.adapter.id === 'image-cli' && Boolean(record.render?.success), cases: record?.adapter.id === 'image-cli' && record.render?.success ? 1 : 0, successful_images: record?.adapter.id === 'image-cli' && record.render?.success ? 1 : 0, revision_non_regression_rate: null }, blocking_failures: ['The full unit suite is not verified.', 'The image-cli adapter has no successful authenticated render.', 'Holdout, visual evaluator evidence, six qualifying live cases, and two real revision loops are missing.'], known_limitations: ['Five Codex imagegen comparison images do not qualify as image-cli adapter evidence.', 'The repository does not include an external holdout suite.'] });
  if (record) await writeFile(resolve(root, 'runs', `${record.runId}.md`), [`# Run ${record.runId}`, '', `Adapter: ${record.adapter.id}`, `Image: ${record.render?.imagePath ?? 'none'}`].join('\n'), 'utf8');
}
