import type { AestheticPlan, CanonicalSceneContract, RendererCapabilities } from '../domain/types.js';
import { grammarFor } from '../domain/grammar-budget.js';

export type AestheticProfile = { id: string; lineDriven?: number; gradientBudget?: number; materialMicrotexture?: number; culturalSpecificity?: number; authoredAsymmetry?: boolean };

export function planAesthetics(contract: CanonicalSceneContract, capabilities: RendererCapabilities, profile: AestheticProfile = { id: 'default', lineDriven: 0.5, gradientBudget: 0.3, materialMicrotexture: 0.2, culturalSpecificity: 0.5, authoredAsymmetry: true }): AestheticPlan {
  const visibleEntities = contract.entities.filter((entity) => contract.presence.find((presence) => presence.targetId === entity.id)?.presence !== 'forbidden');
  const ranked = visibleEntities.map((entity, index) => ({ targetId: entity.id, rank: index + 1, semanticWeight: contract.narrativeWeights[entity.id] ?? Math.max(0.1, 0.8 - index * 0.1), visualWeight: contract.saliencyWeights[entity.id] ?? (index ? 0.4 : 1), detailBudget: index ? 0.35 : 0.9 })).sort((a, b) => b.visualWeight - a.visualWeight).slice(0, 3).map((x, i) => ({ ...x, rank: i + 1 }));
  const target = ranked[0]?.targetId;
  const style = contract.stylePreferences[0]?.style ?? 'neutral';
  const actions = grammarFor(style).actions;
  const pose = target && contract.explicitPose[target] ? [`${target}: ${contract.explicitPose[target]}`] : ['Preserve explicit pose and translate emotion into visible weight shift, shoulders, hands and gaze.'];
  return { schemaVersion: '2.2.1', visualThesis: `${target ? 'Protect the primary subject' : 'Keep the scene legible'} while preserving the user's hard constraints.`, focalHierarchy: ranked, composition: { ...contract.composition, focalPath: ranked.map((x) => x.targetId), protectedRegions: ranked.map((x) => x.targetId) }, poseDynamics: { directives: pose, gravity: ['All hanging, liquid and fabric elements follow gravity.'], inertia: ['Motion direction is coherent with body momentum and contact.'] }, formLighting: { source: 'soft directional key', direction: 'from upper front unless explicitly specified', facePlanes: target ? [`Keep structural light on ${target}`] : [] }, shapeLanguage: { entityRules: Object.fromEntries(visibleEntities.map((x) => [x.id, [`preserve ${x.type} identity`, 'avoid unrequested substitutions']])) }, faceIdentity: target && visibleEntities.find((x) => x.id === target)?.type.match(/person|woman|man|face|mechanic|astronomer|gardener|traveler/i) ? { targetId: target, contour: 'distinctive head-to-jaw proportion', eyeShape: 'specific eye aperture rather than generic large eyes', browEyeAxis: 'asymmetric brow-eye relation', noseMouth: 'declared nose-mouth spacing', asymmetry: 'subtle non-destructive asymmetry', recognitionPoint: 'hairline or ear/side-profile cue', expressionDeformation: 'expression changes eyelids, cheeks and mouth corners', lightStableFeature: 'recognition point survives key light' } : undefined, expression: [], informationBudget: { foreground: 0.7, midground: 0.45, background: 0.2, texture: profile.materialMicrotexture ?? 0.2, estimatedConcepts: visibleEntities.length + contract.relations.length + actions.length }, renderingGrammar: { ...grammarFor(style), actions }, sceneCredibility: { functionalDetails: ['Preserve visible contact, support and use relationships.'], culturalAnchors: profile.culturalSpecificity && profile.culturalSpecificity > 0.6 ? ['Prefer concrete context cues only when user-specified or evidenced.'] : [], usageTraces: ['Do not add generic decorative background detail.'] }, controlledFreedom: contract.freedomSlots.map((x) => ({ area: x.area, allowed: x.allowed, budget: 0.2 })), decisions: [{ target: target ?? 'scene', reason: 'Allocate the highest attention budget to the first declared or explicitly salient subject.', affectedNodes: target ? [target] : [], priority: 1, degradable: false, source: `profile:${profile.id}` }, { target: 'background', reason: 'Limit background detail to protect semantic readability.', affectedNodes: [], priority: 0.7, degradable: true, source: `capability:${capabilities.id}` }] };
}
