import type { AestheticPlan, AttentionBudget, CanonicalSceneContract, ComplexityLevel, RenderIntent221, StagePlan } from '../domain/types.js';
import { contractHash } from '../core/constraint-core.js';
import { createHash } from 'node:crypto';

const digest = (value: unknown) => createHash('sha256').update(JSON.stringify(value)).digest('hex');
const visibleEntities = (contract: CanonicalSceneContract) => contract.entities.filter((entity) => contract.presence.find((presence) => presence.targetId === entity.id)?.presence !== 'forbidden');
const countHard = (contract: CanonicalSceneContract) => contract.presence.filter((x) => x.presence !== 'optional').length + contract.identityInvariants.filter((identity) => visibleEntities(contract).some((entity) => entity.id === identity.targetId)).length + contract.spatialInvariants.filter((x) => x.hard).length + contract.forbiddenOutcomes.length;
export function attentionBudget(contract: CanonicalSceneContract, plan: AestheticPlan): AttentionBudget { return { entityCount: visibleEntities(contract).length, hardConstraintCount: countHard(contract), relationCount: contract.relations.length, highPrecisionRegions: plan.faceIdentity ? 1 : 0, physicsEvents: plan.poseDynamics.gravity.length + plan.poseDynamics.inertia.length, lightSources: plan.formLighting.source ? 1 : 0, textBrandRequirements: 0, styleRequirements: plan.renderingGrammar.actions.length, negativeConstraints: contract.forbiddenOutcomes.length + contract.semanticOpenness.reduce((n, x) => n + x.forbiddenNarrowing.length, 0), estimatedConceptDensity: plan.informationBudget.estimatedConcepts + countHard(contract) } }
export function complexityGate(budget: AttentionBudget, caps: { threshold?: number; staged?: boolean }): ComplexityLevel { const threshold = caps.threshold ?? 24; if (budget.estimatedConceptDensity > threshold * 1.5) return 'unsupported'; if (budget.estimatedConceptDensity > threshold || (budget.entityCount >= 4 && budget.relationCount >= 2)) return caps.staged === false ? 'staged_recommended' : 'staged_required'; if (budget.highPrecisionRegions && budget.physicsEvents >= 2) return 'staged_recommended'; return 'single_pass'; }
const stagePlan = (level: ComplexityLevel): StagePlan => ({ level, stages: level === 'single_pass' ? [{ stage: 1, focus: ['composition', 'entities', 'constraints', 'style'], locked: ['hard items'] }] : [{ stage: 1, focus: ['composition', 'entities', 'count', 'space', 'motion', 'gravity'], locked: ['identity', 'presence', 'forbidden'] }, { stage: 2, focus: ['identity', 'face', 'hands', 'clothing', 'key props'], locked: ['stage 1'] }, { stage: 3, focus: ['credibility', 'culture', 'text', 'usage traces'], locked: ['stage 1', 'stage 2'] }, { stage: 4, focus: ['lighting', 'color', 'material restraint', 'local refinement'], locked: ['all hard items'] }] });
export const COMPILER_PASSES = ['Identity Pass', 'Presence Pass', 'Spatial/Scale Pass', 'Event/Motion Pass', 'Attention Pass', 'Aesthetic Lowering Pass', 'Information Compression Pass', 'Negative Constraint Pass', 'Staging Pass', 'Sanitizer'] as const;
export function compile221(contract: CanonicalSceneContract, plan: AestheticPlan, options: { staged?: 'auto' | 'on' | 'off'; threshold?: number } = {}): RenderIntent221 {
  const budget = attentionBudget(contract, plan); const level = options.staged === 'on' ? 'staged_required' : options.staged === 'off' ? complexityGate(budget, { staged: false, threshold: options.threshold }) : complexityGate(budget, { threshold: options.threshold });
  const entityMappings = visibleEntities(contract).map((x) => ({ entityId: x.id, instruction: `Render ${x.label} as ${x.type}; preserve identity and affordances.` }));
  const hardItems = [...contract.entities.filter((x) => contract.presence.find((p) => p.targetId === x.id)?.presence === 'required').map((x) => `required entity: ${x.label}`), ...contract.forbiddenOutcomes.map((x) => `forbidden: ${x.target}`), ...contract.semanticOpenness.flatMap((x) => x.forbiddenNarrowing.map((y) => `do not narrow ${x.targetId} to ${y}`))];
  const positive = [contract.sceneIdentity ? `Scene: ${contract.sceneIdentity}` : 'Keep the scene identity legible.', ...entityMappings.map((x) => x.instruction), ...contract.relations.map((x) => `Relation: ${x.subject} ${x.type} ${x.object}.`), ...Object.entries(contract.explicitPose).map(([x, y]) => `Pose ${x}: ${y}.`), ...plan.poseDynamics.gravity, ...plan.poseDynamics.inertia, ...plan.renderingGrammar.actions, `Visual thesis: ${plan.visualThesis}`];
  const negative = [...contract.forbiddenOutcomes.map((x) => `Do not render ${x.target}.`), ...contract.semanticOpenness.flatMap((x) => x.forbiddenNarrowing.map((y) => `Do not collapse ${x.targetId} into ${y}.`))];
  return { kind: 'vast.render-intent', schemaVersion: '2.2.1', prompt: [...positive, ...negative].join(' '), positiveInstructions: positive, negativeConstraints: negative, entityMappings, composition: plan.composition, physics: [...plan.poseDynamics.gravity, ...plan.poseDynamics.inertia], lighting: [plan.formLighting.source, plan.formLighting.direction, ...plan.formLighting.facePlanes], informationBudget: plan.informationBudget, staging: stagePlan(level), softItems: plan.controlledFreedom.flatMap((x) => x.allowed), hardItems, compressionAudit: { removed: ['generic praise adjectives', 'duplicated low-priority style words'], merged: ['entity identity and affordance instructions'], downgraded: budget.estimatedConceptDensity > 24 ? ['background texture detail'] : [] }, outputModality: contract.outputModality, provenance: { contractHash: contractHash(contract), aestheticPlanHash: digest(plan) } };
}
